name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: '*'

jobs:
  build:
    name: ${{ matrix.os }}::node:${{ matrix.node }} build - lint - test
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        node: [ 16.x ]
        os: [ ubuntu-latest, windows-latest ]

    steps:
      - name: checkout repository
        uses: actions/checkout@v2

      - name: use node version ${{ matrix.node }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: install dependencies
        uses: bahmutov/npm-install@v1

      - name: lint
        run: yarn lint

      - name: build
        run: yarn build

      - name: generate api
        run: yarn generate:api

      - name: test
        run: yarn cover
